# API Keys,.sensitive data,credentials
# Gitleaks - marketplace
name: Secrets Scan  

on:
  workflow_call: 

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
        with:
          fetch-depth: 1

      - name: Run Gitleaks scanner
        uses: gitleaks/gitleaks-action@v2  # Action to detect secrets like API keys, passwords
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides a temporary token for workflow API access.
