name: Deploy personal notes app
on:
  workflow_dispatch: 
  # workflow_run:
  #   workflows: ["Docker Build & Push"]
  #   types: [completed]
  #   branches: [main]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKER_TAG: ${{ github.sha }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Clear Docker data
        run: |
         docker compose down -v || true
         docker system prune -af

      - name: Deploy with Docker Compose
        run: |
         docker compose build --no-cache
         docker compose up -d --force-recreate
