name: Devsecops end to end pipeline

on:
  workflow_dispatch: 
  # push: 
  #  branches: [main]

jobs:
    # CI with security scanning
    code-quality-check:
        uses: ./.github/workflows/1.code-quality.yml
        
    secret-scan:
        uses: ./.github/workflows/2.secrets-scan.yml
        secrets: inherit
        
    dependency-vulnerability-scan:
        uses: ./.github/workflows/3.dependency-scan.yml
    
    dockerfile-lint:
        uses: ./.github/workflows/4.docker-lint.yml

  # Build after security scanning done
    docker-build-and-push:
       needs: [code-quality-check, secret-scan, dependency-vulnerability-scan, dockerfile-lint]
       uses: ./.github/workflows/docker-build-push.yml
       secrets: inherit

    container-image-scan-trivy:
      needs: [docker-build-and-push]
      uses: ./.github/workflows/images-scan.yml
      secrets: inherit

    # CD : Deploy to Server
    deploy-to-server:
        needs: [container-image-scan-trivy]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit
