name: Devsecops end to end pipline

on:
  workflow_dispatch:

jobs:
    code-quality:
        uses: ./.github/workflows/1.code-quality.yml
        
    secrets-scan:
        uses: ./.github/workflows/2.secrets-scan.yml
        secrets: inherit
        
    dependency-scan:
        uses: ./.github/workflows/3.dependency-scan.yml
    
    docker-scan:
        uses: ./.github/workflows/4.docker-lint.yml
