name: Devsecops end to end pipeline

on:
  push: 
   branches: [main]

jobs:
    # CI with security scanning
    code-quality:
        uses: ./.github/workflows/1.code-quality.yml
        
    secrets-scan:
        uses: ./.github/workflows/2.secrets-scan.yml
        secrets: inherit
        
    dependency-scan:
        uses: ./.github/workflows/3.dependency-scan.yml
    
    docker-scan:
        uses: ./.github/workflows/4.docker-lint.yml

  # Build after security scanning done
    build:
       needs: [code-quality,secrets-scan,dependency-scan,docker-scan]
       uses: ./.github/workflows/docker-build-push.yml
       secrets: inherit

    trivy:
      needs: [build]
      uses: ./.github/workflows/images-scan.yml
